version: "3.8"
services:
  web_emisiones:
    container_name: contenedor_web_emisiones
    build: .
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db_emisiones

  db_emisiones:
    container_name: contenedor_db_emisiones
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1DAW3_BBDD
      MYSQL_DATABASE: CineDB
    ports:
      - "3309:3306"
